### ISSUE TITLE
modify readme.md

### ISSUE THREAD

**Issue by argonautica** [hadshirt/sorting-algorithms#22]
edit readme so that it has the names of all the sorting algorithms that are in the repo
perhaps links to files with descriptions of each?

**Comment by insaurabh** [comment]
@hadshirt Can i work on the readme documentation?

**Comment by argonautica** [comment]
> @hadshirt Can i work on the readme documentation?

sure, go for it

**Comment by NatClamp** [comment]
Hey - I noticed that in the readme you talk about naming the folder with the name of the sorting algorithm, but the folders are actually named with the languages. It might be a bit confusing! Shall I correct this?

**Comment by whitek2** [comment]
Hiyah!
I added to the readme and created a pull request! :)
