### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by argonautica** [hadshirt/sorting-algorithms#85]
can someone update the readme with all the files that are present in the repo?
some haven't been added to the table yet. 
also, detailed instructions for newcomers on how to update the readme with the names of files that they add would be nice. 
thanks :)

**Comment by rgenchev** [comment]
Can I work on this? Thanks in advance :)

**Comment by rgenchev** [comment]
I created https://github.com/hadshirt/sorting-algorithms/pull/87.
